title: Rico Fornes
description: a cybersecurity enthusiast.
show_downloads: true
social:
  linkedin: "https://www.linkedin.com/in/yourprofile"
  instagram: "https://www.instagram.com/yourprofile"
  github: "https://github.com/yourprofile"
google_analytics:
theme: jekyll-theme-hacker

