title: Rico Fornes
description: a cybersecurity enthusiast.
google_analytics:
theme: jekyll-theme-hacker
social:
  linkedin: "https://www.linkedin.com/in/rico-fornes"
  instagram: "https://www.instagram.com/ricoswabii"
  github: "https://github.com/ricoswabii"

