title: Rico Fornes
description: a cybersecurity enthusiast.
show_downloads: true
google_analytics:
theme: jekyll-theme-hacker

social:
  LinkedIn: "https://www.linkedin.com/in/yourprofile"
  Instagram: "https://www.instagram.com/yourprofile"
  

